name: CI/CD

on:
  push:
    branches:
      - main
      - dev

env:
  subscription-name: Desenvolvimento
  TF_TOKEN_app_terraform_io: 9bKD6MWGovtLcw.atlasv1.uZwqmceB7t0yIZM6eM6WUpzNlGBWlSpNeNXp3CyCrto6W9c0UTXp27zLWxtOdBEOviU
  TF_CLOUD_ORGANIZATION: Fernandinho
  TF_WORKSPACE: teste-esteira-dev

jobs:
  build:
    defaults:
      run:
        working-directory: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "terraform"

      - name: Setup Git
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://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@github.com/".insteadOf "https://github.com/"
      
      - name: Az CLI login
        uses: azure/login@v2
        with:
          creds: '{"clientId": "fc86d2f0-2238-4977-8e7e-973a06cc404a","clientSecret": "qas8Q~tQPHCGtJKTNjG3ZP~kV4QPQWVZrM9-Xbsa","subscriptionId": "${{env.subscription-name}}","tenantId": "f8d886ff-2097-4c25-96a8-6dc1a287954d"}'

      - name: Create credentials.tfrc.json
        run: |
          cat <<EOF > credentials.tfrc.json
          {
            "credentials": {
              "app.terraform.io": {
                "token": "${{ env.TF_TOKEN_app_terraform_io }}"
              }
            }
          }
          EOF

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Generate subscription provider
        run: |
          SUB_ID=$(az account list --query "[?name=='${{ env.subscription-name }}'].id" -o tsv)
          cat <<EOF > subscription.tf
          provider "azurerm" {
            features {}
            subscription_id = "$SUB_ID"
          }
          EOF
      - name: Terraform Login
        run: terraform login

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan