name: CI/CD

on:
  push:
    branches:
      - main
      - dev

env:
  subscription-name: Desenvolvimento

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "terraform"

      - name: Setup Git
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://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@github.com/".insteadOf "https://github.com/"
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Generate subscription file
        run: |
          echo "TF_VAR_ARM_SUBSCRIPTION_ID = \"${{ env.subscription-name }}\"" > terraform/subscription.auto.tfvars

      - name: Setup HCP Terraform
        run: |
          echo "9bKD6MWGovtLcw.atlasv1.uZwqmceB7t0yIZM6eM6WUpzNlGBWlSpNeNXp3CyCrto6W9c0UTXp27zLWxtOdBEOviU" > .terraformrc

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan